package com.tsoft.jdistella;

public class JDiMaria {

    public static String[] maria = new String[] {
        "$00",
        "INPTCTRL",
        "$02",
        "$03",
        "$04",
        "$05",
        "$06",
        "$07",
        "INPT0",
        "INPT1",
        "INPT2",
        "INPT3",
        "INPT4",
        "INPT5",
        "$0E",
        "$0F",
        "$10",
        "$11",
        "$12",
        "$13",
        "$14",
        "AUDC0",
        "AUDC1",
        "AUDF0",
        "AUDF1",
        "AUDV0",
        "AUDV1",
        "$1B",
        "$1C",
        "$1D",
        "$1E",
        "$1F",
        "BACKGRND",
        "P0C1",
        "P0C2",
        "P0C3",
        "WSYNC",
        "P1C1",
        "P1C2",
        "P1C3",
        "MSTAT",
        "P2C1",
        "P2C2",
        "P2C3",
        "DPPH",
        "P3C1",
        "P3C2",
        "P3C3",
        "DPPL",
        "P4C1",
        "P4C2",
        "P4C3",
        "CHBASE",
        "P5C1",
        "P5C2",
        "P5C3",
        "OFFSET",
        "P6C1",
        "P6C2",
        "P6C3",
        "CTRL",
        "P7C1",
        "P7C2",
        "P7C3"
    };

    public static String[] mariaio = new String[] {
        "SWCHA",
        "SWACNT",
        "SWCHB",
        "SWBCNT"
    };

    public static String[] pokey = new String[] {
        "AUDF2",
        "AUDC2",
        "AUDF3",
        "AUDC3",
        "AUDF4",
        "AUDC4",
        "AUDF5",
        "AUDC5",
        "AUDCTL",
        "$4009",
        "RANDOM",
        "$400B",
        "$400C",
        "$400D",
        "$400E",
        "SKCTLS"
    };
}
